name: CI

on:
  push:
    branches: [main, staging]
  pull_request:

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-22.04

    env:
      PKG_CONFIG_PATH: "/usr/lib/x86_64-linux-gnu/pkgconfig"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install JSCoreGTK 4.0
        run: |
          sudo apt update && sudo apt --fix-missing install
          sudo apt-get install -y libjavascriptcoregtk-4.1-0 libjavascriptcoregtk-4.1-dev

      - name: Install system dependencies for Tauri
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libayatana-appindicator3-dev \
            libsoup-3.0-dev \
            build-essential \
            curl \
            pkg-config \
            libssl-dev \
            webkit2gtk-4.1-dev

      - name: Install npm dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Build
        run:  |
          cd src-tauri
          cargo build --verbose

      - name: Run tests
        run: |
          cd src-tauri
          cargo test --verbose

      - name: Lint (optional)
        run: |
          cd src-tauri
          cargo fmt -- --check
